### PR TITLE
add event pow delegation kind 5970.

### PR DESCRIPTION
**Pull request by kehiy**

### CODE REVIEW

**Comment by kehiy** [comment]
@believethehype can you review this, please?

**Comment by believethehype** [comment]
I think it's fine. Only thing that maybe should be clarified more is the Security part in the end. Nip90 has a mechanism to encrypt content with the 'encrypted' Tag. It then should be Nip44 (or as Fallback Nip04) encrypted as defined in the NIP.

**Comment by believethehype** [comment]
Also check the response, it should be 6970 and not 5970

**Comment by kehiy** [comment]
> Also check the response, it should be 6970 and not 5970

fixed.

**Comment by kehiy** [comment]
> I think it's fine. Only thing that maybe should be clarified more is the Security part in the end. Nip90 has a mechanism to encrypt content with the 'encrypted' Tag. It then should be Nip44 (or as Fallback Nip04) encrypted as defined in the NIP.

i meant nip-90 encryption defined in nips repo. should i clarify this?

**Comment by kehiy** [comment]
@believethehype kind number fixed.

**Comment by believethehype** [comment]
> > I think it's fine. Only thing that maybe should be clarified more is the Security part in the end. Nip90 has a mechanism to encrypt content with the 'encrypted' Tag. It then should be Nip44 (or as Fallback Nip04) encrypted as defined in the NIP.
> 
> i meant nip-90 encryption defined in nips repo. should i clarify this?

Yeah, the giftwrap part otherwise might confuse people, so maybe just refer to the encryption part of NIP90.

**Comment by kehiy** [comment]
@believethehype fixed.

**Review by believethehype — APPROVED** [review]

**Pull request merged**
